apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-publisher-internal
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: publisher
  policyTypes:
    - Egress
  egress:
    # Allow DNS
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow communication only to other app services
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: editor
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: renderer
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: assets
      ports:
        - protocol: TCP
          port: 8080
