apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-assets
  {{- if and .Values.s3.eks.enabled .Values.s3.eks.assumeRoleAarn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.s3.eks.assumeRoleArn}}
  {{- end }}
  