apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-assets-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-assets-role
subjects:
  - namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
    name: {{ .Release.Name }}-assets